
- name: Prefer stellarium-bin to stellarium that needs to be compiled
  community.general.pacman:
    name: stellarium
    state: absent
    extra_args: --recursive

- name: Install Stellarium-bin
  become_user: yaywalker
  kewlfft.aur.aur:
    name: stellarium-bin
    state: present
  become: true
