- name: Install reflector to manage mirrorlist
  become_user: yaywalker
  kewlfft.aur.aur:
    use: yay
    name:
      - reflector

- name: Configure reflector
  copy:
    dest: /etc/xdg/reflector/reflector.conf
    content: |
      --save /etc/pacman.d/mirrorlist
      --country Australia
      --protocol https
      --latest 5
      --sort rate
  # become: true
  # become_user: root
  # become_method: ansible.builtin.sudo

- name: update the system
  kewlfft.aur.aur:
    upgrade: yes
    use: yay
