---
-
- name: Ensure users are present with zsh shell and home directories
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell: /usr/bin/zsh
    create_home: yes
    groups: "{{ item.groups | default(omit) }}"
  loop:
    - name: thys
      groups: wheel
    - name: bro
      groups: wheel
    - name: pia
  become_user: root

- name: Ensure sudoers file allows 'wheel' group members to have passwordless sudo
  community.general.sudoers:
    name: wheel-nopasswd
    state: present
    user: "%wheel"
    commands: ALL
    nopassword: yes
  become_user: root

- name: Create the yaywalker user
  become: true
  ansible.builtin.user:
    name: yaywalker
    create_home: yes
    group: wheel
  become_user: root

- name: Allow the `yaywalker` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'yaywalker ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'
  become_user: root
